=== iSPIRT/UFAMS/schemas/flight-log/v1/to-be-signed.json
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "flight-log-schema-v1",
    "type": "object",
    "title": "Flight Log schema for Digital Sky",
    "required": [
		"sequenceNo",
		"permissionArtefactId",
		"previousSequenceNo",
		"logEntries"
    ],
    "properties": {
		"sequenceNo":{
			"$id":"/properties/sequenceNo",
			"type":"number",
			"title": "Flight Log Sequence No"
		 },
		"permissionArtefactId":{
			"$id":"/properties/permissionArtefactId",
			"type":"string",
			"title": "Permission Artefact Id"
		 },
		 "previousSequenceNo": {
			"$id": "#/properties/previousSequenceNo",
			"type": "number",
			"title": "Sequence number of previous flight log"
		},
		"logEntries": {
			"$id": "#/properties/logEntries",
			"type": "array",
			"title": "The flight log entries schema",
			"items": {
				"$id": "#/properties/logEntries/items",
				"type": "object",
				"title": "Flight Log items",
				"required": [
					"entryType",
					"timestamp",
					"longitude",
					"latitude",
					"altitude"
				],
				"properties": {
					"entryType": {
						"$id": "#/properties/logEntries/items/properties/entryType",
						"type": "string",
						"enum": [
							"GEOFENCE_BREACH",
							"TAKEOFF/ARM",
							"TIME_BREACH",
							"LAND/DISARM"
						],
						"title": "Flight Log entries",
						"description": "Every entry in the flight log should be one of the four types"
					},
					"timestamp": {
						"$id": "#/properties/logEntries/items/properties/timestamp",
						"type": "integer",
						"title": "Unix timestamp of the recorded entry",
						"default": 0
					},
					"longitude": {
						"$id": "#/properties/logEntries/items/properties/longitude",
						"type": "number",
						"title": "The longitude in decimal degrees according to WGS-84 system",
						"default": 0,
						"examples": [
							12.34567
						]
					},
					"latitude": {
						"$id": "#/properties/logEntries/items/properties/latitude",
						"type": "number",
						"title": "The latitude in decimal degrees according to WGS-84 system",
						"default": 0,
						"examples": [
							12.34567
						]
					},
					"altitude": {
						"$id": "#/properties/logEntries/items/properties/altitude",
						"type": "number",
						"title": "The ellipsoidal height in m",
						"default": 0,
						"examples": [
							100.1
						]
					}
				}
			}
		}
    }
}

=== iSPIRT/UFAMS/schemas/flight-log/v1/to-be-signed-sample.json
{
	"permissionArtefactId": "0b68382f-29e4-4261-ac40-e1e4e306a247",
	"sequenceNo": 25,
	"previousSequenceNo": 24,
    "logEntries": [
        {
            "entryType": "TAKEOFF/ARM",
            "timestamp": 1583387467 ,
            "longitude": 38.25,
            "latitude": 44.96,
            "altitude": 704.34
        },
        {
            "entryType": "GEOFENCE_BREACH",
            "timestamp": 1583388467 ,
            "longitude": 38.25,
            "latitude": 44.96,
            "altitude": 7
        },
        {
            "entryType": "TIME_BREACH",
            "timestamp": 1583389467 ,
            "longitude": 38.25,
            "latitude": 44.96,
            "altitude": 560
        },
        {
            "entryType": "LAND/DISARM",
            "timestamp": 1583397467 ,
            "longitude": 38.25,
            "latitude": 44.96,
            "altitude": 560
        }
    ]
}
